plan error::outer(
) {
  run_plan('error::inner')
}
